### ISSUE TITLE
Poprawiony plik yaml

### ISSUE THREAD

**Issue by arvelinger** [CERT-Polska/karton-playground#7]
Cześć CERT,

poprawiłem nieco Wasz plik yaml. Teraz plik compose jest taki spisany aby użytkownik mógł to uruchomić na dowolnej maszynie i połączyć się po adresie serwera a nie po localhoście. Poprawiłem też składnię w minio i ekspozycję portów. 
Bez tych poprawek nie chciał się wyświetlać panel od minio. Dodałem także healtcheck dla minio :)

[ENG]

Hi CERT,

I corrected your yaml file a bit. Now the compose file is written in such a way that the user can run it on any machine and connect using the server address, not the localhost. I also improved minio syntax and port exposure.
Without these corrections, the minio panel did not want to be displayed. I also added healtcheck for minio :)

```
version: "3.3"
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mwdb
      MINIO_ROOT_PASSWORD: mwdbmwdb
    volumes:
      - ./minio/data/:/data
      - ./minio/conf/:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: mwdb
      POSTGRES_DB: mwdb
      POSTGRES_PASSWORD: mwdbsecretpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "8379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  mwdb:
    build:
      context: .
      dockerfile: docker/Dockerfile-mwdb
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
      - ./config/mwdb.ini:/app/mwdb.ini
    environment:
      MWDB_REDIS_URI: "redis://redis/"
      MWDB_POSTGRES_URI: "postgresql://mwdb:mwdbsecretpass@postgres/mwdb"
      MWDB_ADMIN_PASSWORD: "admin"
      UWSGI_PROCESSES: 4
    ports:
      - "8080:8080"
  karton-system:
    image: certpl/karton-system:158d07960d8cd39dee8771af719f560df93b3212
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
    entrypoint: karton-system
    command: --setup-bucket
  karton-classifier:
    image: certpl/karton-classifier:320c99de8e05ff3d029609e73ac31bcf2d0ba56c
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
  karton-dashboard:
    image: certpl/karton-dashboard:2c35fb3cae399dba8913f8ad1be9dd6b820b1fd6
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
    ports:
      - "8030:5000"
  karton-mwdb-reporter:
    image: certpl/karton-mwdb-reporter:a4a5a2ece14073e3a25a38bd5f1b0fa14ba725d3
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini



```
